services:
  database:
    container_name: lms
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - lms-main
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
  #      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - lms-main
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6382:6379"
    networks:
      - lms-main
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

networks:
  lms-main:
    driver: bridge

volumes:
  mysql-data:
  redis-data:


